### ISSUE TITLE
Deploy script seems broken

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-mf2-feed#14]
The latest version was not deployed yet.

**Comment by dshanske** [comment]
@pfefferle You switched to Github actions on some of the other plugins. How was that working for you?

**Comment by pfefferle** [comment]
I have no action that runs the unit tests yet

**Comment by dshanske** [comment]
I was thinking of the deploy scripts. But let me see what I can figure out.

**Comment by pfefferle** [comment]
If you/we can be sure the code is tested before we build a tag, then sure! The github actions scripts are way easier than Travis.

**Comment by dshanske** [comment]
I will double check, I tested it last month... will do a second test tonight

**Comment by dshanske** [comment]
@pfefferle It is working to spec as of now.

**Comment by pfefferle** [comment]
I think you got me wrong... I meant it in general... If we can get sure, that the unit tests are green, we can use the github publish workflows, because I do not have worked with github actions and phpunit...

**Comment by dshanske** [comment]
I may be still misunderstanding. I will see if there are any articles that talk about how to do this.

**Comment by dshanske** [comment]
@pfefferle I deployed the 10up deploy to wordpress.org Github action on my Simple Location repository. It is identical to the functionality of the deploy script and is triggered when there is a tag in the master repo. Do you have the password for the indieweb account to add as a secret?

**Comment by dshanske** [comment]
The unit tests would be run when you pushed to master, and the action won't trigger till you tag it with the release number.

**Comment by pfefferle** [comment]
I added the secrets... Are you on a Mac using 1Password?

**Comment by dshanske** [comment]
No, Linux. Is it in the indieweb 1password account?

**Comment by dshanske** [comment]
Either way, are you comfortable with me doing a PR to remove the travis deploy script in favor of the 10Up Github Actions one?

**Comment by dshanske** [comment]
@pfefferle Submitted for your consideration

**Comment by dshanske** [comment]
If this works.. maybe replace it everywhere?
