### ISSUE TITLE
Flush Rewrite Rules

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-mf2-feed#2]
When I activated the plugin, I had to manually flush the rewrite rules to get it to work.

**Comment by pfefferle** [comment]
The flush is implement, no idea why it haven‘t worked for you.

**Comment by ghost** [comment]
I installed and activated the plugin from my WP Dashboard. After, I found my /feed/mf2/ urls are 404s. I flushed the rewrite rules (Dashboard -> Settings -> Permalinks -> Save Changes).

Works now.

**Comment by dshanske** [comment]
I had to do the same

**Comment by dshanske** [comment]
But novice users won't know
