### ISSUE TITLE
Support Content Negotiation

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-mf2-feed#6]
Noticed that @aaronpk does this on his site. If you tell it you want application/mf2+json it will return that.

**Comment by aaronpk** [comment]
I only did this to support retuning activitystreams data for my Mastodon integration. In the process, it wasn't a lot more work to add the mf2 JSON as well.

I would not recommend doing this any time soon tho, as it opens up a bunch of new edge cases and new ways it can fail especially in the Wordpress ecosystem. 

Getting content negotiation to work with the variety of caching plugins will definitely be a challenge and will likely cause a lot of support requests until it's all ironed out. You'll also need to find an Accept value parser as that syntax is more complicated than just string matching.

**Comment by dshanske** [comment]
Oh well

**Comment by dshanske** [comment]
It sounded so easy

**Comment by dshanske** [comment]
Consuming it should be easy enough though

**Comment by dshanske** [comment]
https://github.com/pfefferle/wordpress-activitypub/issues/78 references a content negotiation issue that @pfefferle and I discussed and a challenge should we try to do it in this plugin.
